[platformio]
default_envs = nodemcuv2

[nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 80000000L

[d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200

[common]
lib_deps =
    oxullo/MAX30100 @ ^1.1.5

lib_ldf_mode = chain+

[env:nodemcuv2]
extends = nodemcuv2, common

[env:d1_mini]
extends = d1_mini, common
